"""Regenerate docs/GATE_LEDGER.md from foundry/tests_protocol.py."""
import re

src = open("foundry/tests_protocol.py", encoding="utf-8").read()
lines = ["# GATE LEDGER — every named check, generated from the suite",
         "*Generated by scripts/gen_gate_ledger.py — regenerate after adding gates; never hand-edit.*",
         "",
         "**Naming rule (adopted 2026-07-16):** `Stage T-n` (hyphenated) = Mode T build stages",
         "(TRANSLATION_PIPELINE.md). `Gate Tnn` (no hyphen) = named checks below. Different families.",
         ""]
for m in re.finditer(r'def (t\d+)\(\):\n\s+print\("([^"]+)"\)', src):
    fn, title = m.groups()
    lines.append(f"## {title}")
    nxt = src.find("\ndef ", m.end())
    body = src[m.end(): nxt if nxt > 0 else len(src)]
    for c in re.finditer(r'check\("(T\d+[a-z]?)",\s*"([^"]+)"', body):
        lines.append(f"- **{c.group(1)}** — {c.group(2)}")
    lines.append("")
open("docs/GATE_LEDGER.md", "w", encoding="utf-8").write("\n".join(lines))
print("ledger regenerated")
