const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert');
// Run with NODE_PATH pointing to Playwright and CHROMIUM_PATH to a Chromium executable.
// Usage: node tools/verify_securities_layout.cjs <repository> <output-dir> [--baseline]
const repo=process.argv[2],out=process.argv[3],isCandidate=!process.argv.includes('--baseline');fs.mkdirSync(out,{recursive:true});
let html=fs.readFileSync(repo+'/web/console_v2.html','utf8').replace('renderTabs();\nwhoami().then(u=>{ paintWho(); if(u){ boot(); } else { currentTab = "welcome"; renderContent(); } });','');
const boot=()=>{
 cfg=JSON.parse(JSON.stringify(TEMPLATE));cfg.assumptions.periods_per_year=12;cfg.assumptions.n_periods=36;
 cfg.assumptions.deposit_products.forEach((p,i)=>p.source_catalog_id='demo-deposit-'+i);cfg.assumptions.lending_products.forEach((p,i)=>p.source_catalog_id='demo-loan-'+i);currentTab='config';window._cfgModule='sec';window._cfgSectionOpen={secaoci:true};window._fsxOpen={s1:true,s2:true,s3:true,s4:false,s5:true};refresh=()=>{};scheduleAutosave=()=>{};
 const flat=value=>({source:'entered',trajectory:'flat',value}),explicit=value=>({source:'entered',trajectory:'explicit',cadence:'month',values:Array(36).fill(value)});
 cfg.assumptions.interest_balance_model={enabled:true,mab_source:{source:'fee_stream_quantity',series_id:'demo'},mab_spec:flat(100),scenario_rate_spec:explicit(.031),deposit_attach_rate_spec:explicit(.9),avg_noninterest_balance_per_mab_spec:explicit(25000),boost_attach_rate_spec:explicit(.1),avg_interest_balance_per_mab_spec:explicit(150000),customer_cost_rate_spec:flat(.035),operating_cash_ratio_spec:flat(.3),operating_cash_yield_spec:flat(.01),frb_stock_ratio_spec:flat(.03),frb_stock_yield_spec:flat(.06)};
 _ibFeeQuantityOptions=()=>[{series_id:'demo',label:'Fee Product > BaaS APIs > Migrated MAB'}];
 cfg.assumptions.fixed_assets={mode:'formula_level',formula_level:{base_spec:flat(0),components:[]}};cfg.assumptions.other_liabilities_mode='formula_level';cfg.assumptions.other_liabilities_model={opening_balance:0,base_spec:flat(0),components:[{name:'Operating lease',terms:[{driver_spec:{source:'linked',link:{kind:'fixed_asset_level',series_id:_FA_BASE_SID}},multiplier_spec:flat(1)},{driver_spec:{source:'linked',link:{kind:'fixed_asset_level',series_id:_FA_BASE_SID}},multiplier_spec:flat(.2)}]},{name:'AP and accrued',terms:[{driver_spec:{source:'linked',link:{kind:'fixed_asset_level',series_id:_FA_BASE_SID}},multiplier_spec:flat(.1)}]}]};window._liabilityUiOpen={0:true,1:true};
 cfg.assumptions.managed_securities_portfolios=[{name:'Investment portfolio',target_source:{series_id:'bank.balance_sheet.equity.end',timing:'prior_period',prior_initialization:'zero'},target_ratio_spec:flat(.3),sleeves:[{name:'US Treasury',classification:'AFS',risk_weight:0,allocation_spec:flat(.8),maturity_rate_spec:flat(.02),yield_spec:explicit(.0464)},{name:'GSE',classification:'AFS',risk_weight:.2,allocation_spec:flat(.15),yield_spec:explicit(.05)},{name:'CRA',classification:'AFS',risk_weight:1,allocation_spec:flat(.05),yield_spec:explicit(.06)}]}];
 renderTabs();renderContent();cfgSelectModule('sec',true);applyInspector(false);
};
(async()=>{
 const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 for(const width of [1920,1440,1366,1024]){
 const p=await b.newPage({viewport:{width,height:1080}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.fulfill({contentType:'application/json',body:'{}'}));await p.goto('http://foundry.test');await p.setContent(html.replace('<script>','<script>window.V3=true;window.V31=true;</script><script>'));await p.evaluate(boot);await p.evaluate(()=>fitControls());
 const inventory=await p.evaluate(()=>({config:JSON.stringify(cfg),controls:[...document.querySelectorAll('#card-sec input,#card-sec select,#card-sec textarea,#card-sec button,#card-sec a')].map(el=>[el.tagName,el.getAttribute('onchange')||el.getAttribute('onclick'),el.value||'',el.tagName==='SELECT'?[...el.options].map(o=>[o.value,o.text]):[]])}));
 const geometry=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,sections:[...document.querySelectorAll('.fsx-sec')].map(s=>({id:s.id,width:s.offsetWidth,height:s.offsetHeight})),bad:[...document.querySelectorAll('#card-sec input,#card-sec select,#card-sec button')].filter(e=>e.offsetParent&&e.closest('.fsx-sec')&&e.getBoundingClientRect().right>e.closest('.fsx-sec').getBoundingClientRect().right+1).map(e=>e.outerHTML.slice(0,120))}));
 fs.writeFileSync(out+'/'+width+'.json',JSON.stringify({errors,geometry,inventory},null,2));
 await p.addStyleTag({content:'#ribbon,#appbar,.appbar,#topbar,.topbar{position:relative!important}'});for(const id of ['s1','s2','s3','s5'])await p.locator('#fsx-'+id).screenshot({path:out+'/'+width+'-'+id+'.png'});
 assert.equal(errors.length,0,errors.join('\n'));if(isCandidate)assert.equal(geometry.overflow,false);if(isCandidate)assert.equal(geometry.bad.length,0,JSON.stringify(geometry.bad));
 if(isCandidate){
 const sourceRects=await p.locator('.fsx-source').evaluate(el=>({select:el.querySelector('select').getBoundingClientRect().bottom,help:el.querySelector('.cu').getBoundingClientRect().top}));assert(sourceRects.help>=sourceRects.select,'Source help overlaps selector');
 await p.locator('#fsx-s1 input[onchange*=cash_yield]').fill('1.7');await p.locator('#fsx-s1 input[onchange*=cash_yield]').dispatchEvent('change');await p.waitForFunction(()=>document.querySelector('#fsx-s1 .fsx-sum').textContent.includes('1.7'));assert.equal(await p.locator('#fsx-s1 .fsx-sum>span').count(),6,'Funding summary dropped fields');
 const before=await p.evaluate(()=>JSON.stringify(cfg));await p.locator('#fsx-s2 .sec-managed-explicit-closed button').first().click();await p.locator('#fsx-s2 textarea').first().fill('3.1\t3.2\t3.3');await p.locator('#fsx-s2 textarea').first().evaluate(el=>el.dispatchEvent(new Event('input',{bubbles:true})));await p.locator('#fsx-s2 .sec-managed-explicit-head button').first().click();assert.equal(await p.evaluate(()=>JSON.stringify(cfg)),before,'Opening/closing schedule changed configuration');
 await p.locator('#fsx-s5 select[onchange*=secManagedYieldSource]').selectOption('curve_library');assert.equal(await p.locator('#fsx-s5 select[onchange*=curve_name]').count(),1,'Curve selection lost');await p.locator('#fsx-s5 select[onchange*=secManagedYieldSource]').selectOption('entered');assert.equal(await p.locator('#fsx-s5 .sec-managed-explicit-closed button').count(),1,'Entered yield schedule lost');
 await p.locator('#fsx-s5 .cfg-grid tbody tr').nth(1).click();assert.equal(await p.locator('#fsx-s5 .cfg-md-head b').innerText(),'GSE');assert.equal(await p.locator('#fsx-s5 .cfg-grid tbody tr').count(),3);
 await p.locator('#fsx-s2 select[onchange*=ibCashInterestBasis]').first().selectOption('average');assert.equal(await p.evaluate(()=>cfg.assumptions.interest_balance_model.affiliated_cash_interest_basis),'average');
 }
 await p.close();console.log('PASS '+width+' layout, inventory and schedule actions');
 }await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
