const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');
const repo=path.resolve(__dirname,'..');
(async()=>{
const html=fs.readFileSync(path.join(repo,'web/console_v2.html'),'utf8').replace('renderTabs();\nwhoami().then(u=>{ paintWho(); if(u){ boot(); } else { currentTab = "welcome"; renderContent(); } });','');
const config=JSON.parse(execFileSync('python3',['-c','import json;from foundry.v2.tests_source_catalog import setup;print(json.dumps(setup()))'],{cwd:repo}));
const b=await chromium.launch({executablePath:process.env.FOUNDRY_CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu','--single-process','--no-zygote'],headless:true}),p=await b.newPage({viewport:{width:1440,height:1000}});let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>r.fulfill({status:200,body:'{}',contentType:'application/json'}));await p.setContent(html);
await p.evaluate(c=>{cfg=c;currentTab='products';refresh=()=>{};scheduleAutosave=()=>{};window._fetchRequests=[];window._fetchRelease=[];window.fetch=()=>{window._fetchRequests.push(1);return new Promise(resolve=>window._fetchRelease.push(resolve));};engStore={engagements:[{slug:'cached',name:'Cached engagement'}]};void toggleEngMenu();},config);
if(!await p.getByText('Cached engagement',{exact:true}).isVisible()||!await p.getByText('+ Save current configuration here',{exact:true}).isVisible())throw Error('menu waited for server');
await p.evaluate(()=>{void toggleEngMenu();void toggleEngMenu();});if(await p.evaluate(()=>_fetchRequests.length)!==1)throw Error('duplicate list request');
await p.evaluate(()=>_fetchRelease.shift()({ok:true,json:async()=>({engagements:[{slug:'new',name:'Fresh engagement'}]})}));await p.waitForFunction(()=>!engStoreRequest);if(!await p.getByText('Fresh engagement',{exact:true}).isVisible())throw Error('background list did not update');
await p.evaluate(()=>{void toggleEngMenu();engStore=null;void toggleEngMenu();});if(!await p.getByText('+ Save current configuration here',{exact:true}).isVisible())throw Error('cold menu blocked save');
await p.evaluate(()=>{void toggleEngMenu();_fetchRelease.shift()({ok:true,json:async()=>({engagements:[{slug:'fresh',name:'Fresh engagement'}]})});});await p.waitForFunction(()=>!engStoreRequest);if(await p.locator('#engMenu').isVisible())throw Error('refresh reopened closed menu');
await p.evaluate(()=>{void toggleEngMenu();_fetchRelease.shift()({ok:false});});await p.waitForFunction(()=>!engStoreRequest);if(!await p.getByText('Fresh engagement',{exact:true}).isVisible()||!await p.getByText('Retry',{exact:true}).isVisible())throw Error('failed refresh lost cached list');
await p.evaluate(()=>{void toggleEngMenu();void toggleEngMenu();window._beforeWriteRequests=_fetchRequests.length;window._writeDone=loadEngStore(true,true);_fetchRelease.shift()({ok:true,json:async()=>({engagements:[{slug:'old',name:'Pre-save list'}]})});});
await p.waitForFunction(()=>_fetchRequests.length===_beforeWriteRequests+1);
await p.evaluate(()=>_fetchRelease.shift()({ok:true,json:async()=>({engagements:[{slug:'saved',name:'Post-save list'}]})}));await p.evaluate(()=>window._writeDone);
if(!await p.evaluate(()=>engStore.engagements[0].slug==='saved'))throw Error('write refresh reused pre-write list');
await p.evaluate(()=>{document.getElementById('engMenu').style.display='none';if(_newNieDetail().fdic_bp_ann!==0)throw Error('new FDIC not zero');cfg.assumptions.nie_detail.fdic_bp_ann=7;if(_ensureNieDetail().fdic_bp_ann!==7)throw Error('saved FDIC changed');const g=cfg.assumptions.deposit_retention_pools[0];g.balance_spec={source:'derived',derived:{activity:{source:'entered',period:'month',amount_spec:{source:'entered',trajectory:'flat',value:1200000}},holding_days_spec:{source:'entered',trajectory:'flat',value:3},share_spec:{source:'entered',trajectory:'flat',value:1},day_count:365}};g.capacity_source='beginning_equity_budget';g.equity_budget={target_leverage_spec:{source:'entered',trajectory:'flat',value:.13}};_depositPoolOpen.add(g.id);_renderContentBody=()=>{document.getElementById('content').innerHTML='<div class="prd-card" data-fam="deposit" data-i="0"><div class="pp-sec" data-pp="setup"><div class="fields">'+fieldsFor('deposit',cfg.assumptions.deposit_products[0],'assumptions.deposit_products.0')+'</div></div></div>';prdGroupSetup();};renderContent();});
for(const label of ['1 · Source balance','2 · Retention & capacity','3 · Swept-out fees'])if(!await p.getByText(label,{exact:true}).isVisible())throw Error('missing pool section '+label);
const saved=await p.evaluate(()=>JSON.stringify(cfg.assumptions.deposit_retention_pools));
await p.getByText('Equity budget inputs',{exact:false}).click();if(!await p.getByText('Equity allocation ratio',{exact:true}).isVisible())throw Error('advanced input inaccessible');
await p.getByText('Balance adjustments',{exact:false}).click();if(!await p.getByRole('button',{name:'+ Balance adjustment'}).isVisible())throw Error('adjustment action lost');
for(const width of [1440,1280]){await p.setViewportSize({width,height:1000});const bounds=await p.locator('.deposit-day-count').evaluate(el=>({width:el.getBoundingClientRect().width,right:el.getBoundingClientRect().right,edge:document.getElementById('content').getBoundingClientRect().right}));if(bounds.width>90||bounds.right>bounds.edge+1)throw Error('day count width / overflow '+JSON.stringify(bounds));}
if(saved!==await p.evaluate(()=>JSON.stringify(cfg.assumptions.deposit_retention_pools)))throw Error('display changed pool inputs');
if(process.env.FOUNDRY_DEPOSIT_SCREENSHOT)await p.screenshot({path:process.env.FOUNDRY_DEPOSIT_SCREENSHOT});if(errors.length)throw Error(JSON.stringify(errors));console.log('PASS immediate cached/cold menu, deduplicated background refresh, error retention, closed-menu safety, FDIC defaults, deposit sections/advanced controls/compact day count/pool config preservation');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
