const {chromium}=require('playwright');const fs=require('fs'),assert=require('assert'),path=require('path');
(async()=>{
const html=fs.readFileSync(process.env.FOUNDRY_CONSOLE_HTML||path.join(__dirname,'console_v2.html'),'utf8').replace('renderTabs();\nwhoami().then(u=>{ paintWho(); if(u){ boot(); } else { currentTab = "welcome"; renderContent(); } });','');
const b=await chromium.launch({executablePath:process.env.FOUNDRY_CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu','--single-process','--no-zygote']});const p=await b.newPage();await p.route('**/*',r=>r.fulfill({status:200,body:'{}'}));await p.goto('http://foundry.test');await p.setContent(html);
await p.evaluate(()=>{cfg=JSON.parse(JSON.stringify(TEMPLATE));currentTab='config';refresh=()=>{};cfgAfterRender=()=>{};window._stOwner=()=>cfg.assumptions.obs_exposures[0];cfg.assumptions.obs_exposures=[{name:'Gateway',fee_streams:[{driver:{params:{coefficient:{kind:'turns',schedule:{'1':2}},flow_path:{schedule:{'1':20}},level_schedule:{schedule:{'1':5}}}}}]}];_renderContentBody=()=>{document.getElementById('content').innerHTML=['feeCoeffPaste','feeEnteredFlowPaste','feeAccountLevelPaste','unrelated'].map(k=>`<div><textarea id="${k}_0_0" oninput="_feeExplicitPasteInput('${k}_0_0')"></textarea><button id="${k}_0_0_load" disabled>Load (replace)</button></div>`).join('')};renderContent();});
for(const [prefix,handler,key] of [['feeCoeffPaste','_feeClearCoeffSchedule','coefficient'],['feeEnteredFlowPaste','_feeClearEnteredFlowSchedule','flow_path'],['feeAccountLevelPaste','_feeClearAccountLevelSchedule','level_schedule']]){
 await p.locator('#'+prefix+'_0_0').fill('2\t3\t4');await p.locator('#unrelated_0_0').fill('retain this draft');
 await p.evaluate(h=>window[h](0,0),handler);
 assert.strictEqual(await p.locator('#'+prefix+'_0_0').inputValue(),'');assert.strictEqual(await p.locator('#unrelated_0_0').inputValue(),'retain this draft');assert(await p.locator('#'+prefix+'_0_0_load').isDisabled());assert.deepStrictEqual(await p.evaluate(k=>cfg.assumptions.obs_exposures[0].fee_streams[0].driver.params[k].schedule,key),{});
 await p.evaluate(()=>renderContent());assert.strictEqual(await p.locator('#'+prefix+'_0_0').inputValue(),'');
}
await p.locator('#feeCoeffPaste_0_0').fill('7\t8');await p.evaluate(()=>renderContent());assert.strictEqual(await p.locator('#feeCoeffPaste_0_0').inputValue(),'7\t8');await p.evaluate(()=>_feeSetCoeffSchedule(0,0,document.getElementById('feeCoeffPaste_0_0').value));assert.deepStrictEqual(await p.evaluate(()=>cfg.assumptions.obs_exposures[0].fee_streams[0].driver.params.coefficient.schedule),{'1':7,'2':8});console.log('PASS three activity Clear handlers: schedule and visible draft cleared, Load disabled, unrelated drafts preserved, rerender stable, replacement loads correct');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
