const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');
const repo=path.resolve(__dirname,'..');
(async()=>{
let html=fs.readFileSync(path.join(repo,'web/console_v2.html'),'utf8').replace('renderTabs();\nwhoami().then(u=>{ paintWho(); if(u){ boot(); } else { currentTab = "welcome"; renderContent(); } });','');
const config=JSON.parse(execFileSync('python3',['-c','import json;from foundry.v2.tests_source_catalog import setup;print(json.dumps(setup()))'],{cwd:repo}));
const browser=await chromium.launch({executablePath:process.env.FOUNDRY_CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu','--single-process','--no-zygote'],headless:true});const page=await browser.newPage({viewport:{width:1400,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{if(route.request().url().includes('/source-catalog')){const body=execFileSync('python3',['-c',"import json,sys;from foundry.v2.source_catalog import catalog;payload=json.load(sys.stdin);c=payload.get('config') or payload;print(json.dumps({'sources':catalog(c['assumptions'])}))"],{cwd:repo,input:route.request().postData()});return route.fulfill({status:200,body,contentType:'application/json'});}return route.fulfill({status:200,body:'{}',contentType:'application/json'});});
await page.goto('http://foundry.test');await page.setContent(html);await page.evaluate(c=>{cfg=c;currentTab='products';refresh=()=>{};scheduleAutosave=()=>{};_renderContentBody=()=>{document.getElementById('content').innerHTML=_opexFormulaDriverEditorHtml(0,0,cfg.assumptions.nie_detail.categories[0].linked_components[0])};renderContent();},config);
await page.evaluate(()=>{cfg.assumptions.nie_detail.categories[0].linked_components=[];nieCatAddFormulaDriver(0);});
if(await page.locator('.fx-linked select').inputValue()!=='')throw Error('new expense preselected a source');
if(await page.locator('.fx-linked select option:checked').textContent()!=='Select a source')throw Error('missing neutral prompt');
await page.evaluate(()=>nieCatFormulaAddLinkedFactor(0,0));
if(!await page.evaluate(()=>cfg.assumptions.nie_detail.categories[0].linked_components[0].factors.filter(f=>f.kind==='linked').every(f=>f.source===''&&!f.series_id)))throw Error('added factor preselected a source');
await page.evaluate(()=>nieCatFormulaRemoveFactor(0,0,2));
await page.getByText('Browse / search',{exact:true}).click();await page.locator('#sourceCatalogSearch').fill('Retained on-book');await page.locator('#sourceCatalogList button').click();
if(!await page.evaluate(()=>cfg.assumptions.nie_detail.categories[0].linked_components[0].factors[0].series_id==='deposit_pool.pool.retainedBalance'))throw Error('source selection failed');
await page.evaluate(()=>{cfg.assumptions.deposit_retention_pools[0].name='Program pool renamed';});await page.getByText('Browse / search',{exact:true}).click();await page.locator('#sourceCatalogSearch').fill('Program pool renamed');if(await page.locator('#sourceCatalogList button').count()!==3)throw Error('renamed metadata not refreshed');await page.getByRole('button',{name:'Close source catalog'}).click();
await page.locator('.fx-linked select').last().selectOption('period_average');if(!await page.evaluate(()=>cfg.assumptions.nie_detail.categories[0].linked_components[0].factors[0].measure==='period_average'))throw Error('measure selection failed');
if(process.env.FOUNDRY_CATALOG_SCREENSHOT){await page.getByText('Browse / search',{exact:true}).click();await page.locator('#sourceCatalogSearch').fill('Program pool renamed');await page.screenshot({path:process.env.FOUNDRY_CATALOG_SCREENSHOT});}
if(await page.locator('dialog[open]').count())await page.getByRole('button',{name:'Close source catalog'}).click();
const result=JSON.parse(execFileSync('python3',['-c','import json;from foundry.v2.tests_source_catalog import setup;from foundry.v2.run_q import run_v2;print(json.dumps(run_v2(setup())))'],{cwd:repo}));
await page.evaluate(r=>{lastRes=r;renderContent();},result);
let preview=await page.locator('.cac-link-readonly').textContent();if(!preview.includes('M1 200')||!preview.includes('M2 400'))throw Error('average preview did not match engine retained balances: '+preview);
await page.locator('.fx-measure select').selectOption('period_end');
if(!(await page.locator('.cac-link-readonly').textContent()).includes('M1 400'))throw Error('end balance preview mismatch');
await page.evaluate(()=>{document.getElementById('content').classList.add('is-config');_renderContentBody=()=>{document.getElementById('content').innerHTML='<div class="cfg-shell"><nav class="cfg-nav">Modules</nav><div style="min-width:0;padding:20px"><section data-nie-pane="categories"><div class="cfg-md"><div class="cfg-md-list">Category list</div><div class="cfg-md-detail"><div class="cfg-md-body">'+_opexFormulaDriverEditorHtml(0,0,cfg.assumptions.nie_detail.categories[0].linked_components[0])+'</div></div></div></section></div></div>'};renderContent();});
for(const width of [1920,1440,1280]){await page.setViewportSize({width,height:1000});for(const closed of [false,true]){await page.evaluate(c=>document.body.classList.toggle('insp-closed',c),closed);await page.evaluate(()=>renderContent());const bounds=await page.evaluate(()=>{const panel=document.querySelector('.cfg-md-detail').getBoundingClientRect(),aside=document.querySelector('main>aside').getBoundingClientRect(),content=document.getElementById('content').getBoundingClientRect(),rm=document.querySelector('.fx-linked .fx-rmc').getBoundingClientRect(),row=document.querySelector('.fx-linked').getBoundingClientRect();return {right:panel.right,edge:document.body.classList.contains('insp-closed')?content.right:aside.left,rmRight:rm.right,rowRight:row.right,rmTop:rm.top,rowTop:row.top}});if(bounds.right>bounds.edge+1||bounds.rmRight>bounds.rowRight+1||bounds.rmTop>bounds.rowTop+40)throw Error('layout overflow / misplaced remove at '+width+' closed='+closed+': '+JSON.stringify(bounds));}}
if(process.env.FOUNDRY_CATALOG_SCREENSHOT){await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>document.body.classList.remove('insp-closed'));await page.screenshot({path:process.env.FOUNDRY_CATALOG_SCREENSHOT});}
if(errors.length)throw Error(JSON.stringify(errors));console.log('PASS production source dialog: search, select retained pool balance, metadata rename, balance measure, no page errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
