const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/console_v2.html','utf8');
const source=html.slice(html.indexOf('// r269: compatible quantity references'),html.indexOf('function _feePctSemantics',html.indexOf('// r269: compatible quantity references')));
const products=[{name:'Consumer',fee_streams:[{name:'Migrated',basis:'transaction',driver:{source:'fee_stream_quantity',params:{}}}]},{name:'Activity',fee_streams:[{name:'TPV',basis:'transaction',driver:{source:'constant',params:{flow_path:{unit_kind:'money_flow'}}}},{name:'Count',basis:'account',quantity_series_id:'count',driver:{source:'constant'}}]},{name:'Downstream',fee_streams:[{name:'Cycle candidate',basis:'transaction',quantity_series_id:'cycle',driver:{source:'fee_stream_quantity',ref:'consumer'}}]}];
products[0].fee_streams[0].quantity_series_id='consumer';
let renders=0,refreshes=0,ids=0;const ctx={cfg:{assumptions:{obs_exposures:products}},_stOwner:i=>products[i],_seriesId:()=>`new-${++ids}`,renderContent:()=>renders++,refresh:()=>refreshes++};vm.createContext(ctx);vm.runInContext(source,ctx);
let options=ctx.feeQuantityCandidates(0,0);assert.equal(options.length,2);assert.equal(ids,0,'Reading choices must not change existing series identity');assert(!options.some(x=>x.value==='cycle'));
ctx.feeQuantitySelect(0,0,'candidate:1:0');const sid=products[1].fee_streams[0].quantity_series_id;assert.equal(sid,'new-1');assert.equal(products[0].fee_streams[0].driver.ref,sid);assert.equal(renders,1);assert.equal(refreshes,1);assert.equal(ctx._feeStreamQuantityKind(0,0),'money');
products[1].name='Renamed';products[1].fee_streams[0].name='Renamed TPV';products.reverse();options=ctx.feeQuantityCandidates(2,0);assert(options.some(x=>x.value===sid&&x.label.includes('Renamed')));
products[2].fee_streams[0].basis='balance';options=ctx.feeQuantityCandidates(2,0);assert(!options.some(x=>x.value===sid));
assert(html.includes('Linked stream quantity — across fee products'));assert(html.includes('if(_fi>=0&&_fi<1000&&'));
console.log('PASS cross-product choices, lazy stable ID, rename/reorder, unit inference, cycle exclusion, stock/flow filtering');
