const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.FOUNDRY_CHROMIUM||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const page=await browser.newPage({viewport:{width:1600,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
let html=fs.readFileSync(__dirname+'/console_v2.html','utf8').replace(/renderTabs\(\);\s*whoami\(\)\.then\([\s\S]*?<\/script>/,'renderTabs();</script>');html=html.replace('</head>','<script>window.V31=true;window.BUILD="r200IQ test";</script></head>');
await page.route('**/*',route=>route.request().url()==='http://foundry.test/'?route.fulfill({contentType:'text/html',body:html}):route.abort());await page.goto('http://foundry.test/');
await page.evaluate(()=>{cfg=buildEmptyTemplate();cfg.proposed_bank='Demonstration Bank';cfg.assumptions.periods_per_year=12;cfg.assumptions.n_periods=36;cfg.assumptions.operating_expense_mode='detailed';cfg.assumptions.nie_detail={workforce:{roles:[{series_id:'wf-a',role:'Platform team',count:140,annual_comp:95000},{series_id:'wf-b',role:'Bank compensation',count:1,annual_comp:287500,compensation_period:'month'},{series_id:'wf-c',role:'Directors fees',count:1,annual_comp:37500,compensation_period:'month'}]},categories:[{series_id:'cat-a',name:'Technology',flow_spec:{trajectory:'flat',value:100000,period:'month'}},{series_id:'cat-b',name:'Internal audit',flow_spec:{trajectory:'flat',value:750000,period:'year'}}]};cfg.assumptions.cac_feeds={customer_build:{series_id:'customer-build',beginning_customers:1200,beginning_auc:0,attrition_rate:0,channels:[{name:'Customer funnel',method:'spend_cac',params:{spend:100000,cac:1000,avg_auc_per_customer:0}}]}};window._cfgSectionOpen.customeracq=true;refresh=()=>{};renderGlobals();currentTab='config';renderTabs();renderContent();});
await page.evaluate(()=>{secManagedAddPortfolio();secManagedAddSleeve(0);nieCatAddFormulaDriver(0);nieCatAddPiecewise(0);nieCatAddCostPoolCharge(0);});
const sections=await page.locator('.iq-nav button').evaluateAll(es=>es.map(e=>e.dataset.iqSection));
assert.equal(sections.length,9);
assert.equal(await page.locator('#tabs > .tab').count(),6);
await page.locator('.iq-more-nav > summary').click();
assert.equal(await page.locator('.iq-more-nav button.tab').count(),await page.evaluate(()=>TAB_DEFS.length-6));
await page.locator('.iq-more-nav > summary').click();
for(const width of [1600,1280,1024,768]){
 await page.setViewportSize({width,height:1050});
 for(const key of sections){
  await page.locator('[data-iq-section="'+key+'"]').click();
  assert.equal(await page.locator('[data-iq-panel]:visible').count(),1);
  const coloredPanels=await page.locator('#iq-workspace :is(.cac-feed-card,.cac-channel-card,.wf-role-card,.sec-managed-portfolio,.opex-piecewise-card)').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height).filter(e=>{const c=getComputedStyle(e).backgroundColor.match(/\d+/g)||[];return c.length>=3&&(Math.max(...c.slice(0,3).map(Number))-Math.min(...c.slice(0,3).map(Number)))>8}).map(e=>e.className));
  assert.deepEqual(coloredPanels,[],`non-neutral panels ${width} ${key}`);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${width} ${key}`);
 }
}
await page.setViewportSize({width:1600,height:1050});
await page.locator('[data-iq-section="card-nie"]').click();
await page.locator('#iq-items-workforce [data-iq-item-button="1"]').click();
assert.equal(await page.locator('#iq-items-workforce [data-iq-item]:visible .wf-role-name').inputValue(),'Bank compensation');
await page.locator('.nie-actions a[onclick*="nieWorkforceAdd();"]').click();
assert.equal(await page.locator('#iq-items-workforce [data-iq-item]:visible').getAttribute('data-workforce-index'),'3');
await page.locator('#iq-items-workforce [data-iq-item]:visible .wf-role-name').fill('New role');
await page.locator('#iq-items-workforce [data-iq-item]:visible .wf-role-name').dispatchEvent('change');
assert.match(await page.locator('#iq-items-workforce [data-iq-item-button="3"]').innerText(),/New role/);
await page.locator('#iq-items-workforce [data-iq-item]:visible .wf-delete').click();
assert.equal(await page.locator('#iq-items-workforce [data-iq-item-button]').count(),3);
await page.locator('#iq-items-workforce [data-iq-item-button="1"]').click();
const role=page.locator('#iq-items-workforce [data-iq-item]:visible');
await role.locator('select[onchange*="nieWorkforceCompMode"]').selectOption('explicit');
await page.locator('#iq-items-workforce [data-iq-item]:visible .iq-schedule-preview button').click();
assert.match(await page.locator('#iq-items-workforce [data-iq-item]:visible .iq-schedule-preview').innerText(),/Schedule preview/);
const ta=page.locator('#wfCompPaste_1');
if(!(await ta.isVisible())) await page.evaluate(()=>_pasteSurfaceOpen('wfCompPaste_1'));
await ta.fill('287.5\t300\t325');
await ta.evaluate(el=>el.setSelectionRange(2,5));
await page.evaluate(()=>{window.iqDraftNode=document.getElementById('wfCompPaste_1');refreshConfigPreviews();});
assert.equal(await page.evaluate(()=>iqDraftNode===document.getElementById('wfCompPaste_1')),true);
assert.equal(await ta.inputValue(),'287.5\t300\t325');
await page.locator('[data-iq-section="iq-funding"]').click();await page.locator('[data-iq-section="card-nie"]').click();
assert.equal(await ta.inputValue(),'287.5\t300\t325');
await page.locator('#wfCompPaste_1_load').click();
assert.deepEqual(await page.evaluate(()=>cfg.assumptions.nie_detail.workforce.roles[1].compensation_spec.values),[287500,300000,325000]);
assert.equal(await page.locator('#wfCompPaste_1').inputValue(),'');
await page.locator('#iq-items-workforce [data-iq-item]:visible .iq-count-settings > summary').click();
await page.locator('#iq-items-workforce [data-iq-item]:visible select[onchange*=nieWorkforceCountMode]').selectOption('explicit');
await page.locator('#wfCountPaste_1').fill('1\t2\t3');
await page.locator('#wfCountPaste_1_load').click();
assert.deepEqual(await page.evaluate(()=>cfg.assumptions.nie_detail.workforce.roles[1].count_spec.values),[1,2,3]);
assert.deepEqual(await page.evaluate(()=>cfg.assumptions.nie_detail.workforce.roles[1].compensation_spec.values),[287500,300000,325000]);
await page.locator('#iq-items-workforce [data-iq-item]:visible .iq-setting').filter({hasText:'Escalation & benefits'}).locator('summary').click();
const load=page.locator('#iq-items-workforce [data-iq-item]:visible .wf-load input');await load.fill('10');await load.dispatchEvent('change');
assert.equal(await page.evaluate(()=>cfg.assumptions.nie_detail.workforce.roles[1].payroll_load_rate),.1);
assert.match(await page.locator('#iq-items-workforce [data-iq-item]:visible .iq-setting').filter({hasText:'Escalation & benefits'}).locator('summary').innerText(),/10% payroll load/i);
await page.locator('.iq-expense-tabs [role=tab]').filter({hasText:'Expense categories'}).click();
await page.locator('#iq-items-expenses [data-iq-item-button="1"]').click();
await page.locator('.nie-actions a[onclick*="nieCatAdd();"]').click();
assert.equal(await page.locator('#iq-items-expenses [data-iq-item]:visible').getAttribute('data-opex-index'),'0');
await page.locator('#iq-items-expenses [data-iq-item]:visible .opex-item-name').fill('Legal');
await page.locator('#iq-items-expenses [data-iq-item]:visible .opex-item-name').dispatchEvent('change');
await page.evaluate(()=>{_iqSelectItem('iq-items-expenses',2);window._nieCatDragIndex=2;window.nieCatDrop({preventDefault(){},currentTarget:document.querySelector('#iq-items-expenses [data-iq-item-button="0"]')},0);});
assert.equal(await page.locator('#iq-items-expenses [data-iq-item]:visible .opex-item-name').inputValue(),'Internal audit');
await page.locator('#iq-items-expenses [data-iq-item]:visible a[onclick*="nieCatDelete"]').click();
assert.equal(await page.locator('#iq-items-expenses [data-iq-item-button]').count(),2);
await page.locator('[data-iq-section="assumptions"]').click();
await page.evaluate(()=>window.iqGlobals=document.getElementById('globalsBox'));
await page.evaluate(()=>setTab('products'));assert.equal(await page.locator('main > aside').isVisible(),true);
await page.evaluate(()=>setTab('config'));assert.equal(await page.locator('main > aside').isVisible(),false);
assert.equal(await page.evaluate(()=>iqGlobals===document.getElementById('globalsBox')),true);
assert.equal(await page.locator('#globalsBox').count(),1);
await page.locator('[data-iq-section="iq-funding"]').click();
await page.getByLabel('Unallocated funding').selectOption('residual_securities');
assert.equal(await page.evaluate(()=>cfg.assumptions.surplus_allocation_policy),'residual_securities');
await page.locator('[data-iq-section="card-tax"]').focus();await page.keyboard.press('ArrowDown');
assert.equal(await page.locator('[data-iq-section="card-cecl"]').getAttribute('aria-selected'),'true');
await page.evaluate(()=>{cfg=buildEmptyTemplate();renderGlobals();renderContent();});
assert.equal(await page.locator('[data-iq-section="assumptions"]').getAttribute('aria-selected'),'true');
assert.equal(await page.locator('#iq-items-workforce').count(),0);
assert.deepEqual(errors,[]);
console.log('PASS populated browser (CAC, managed securities, formula/tiered/cost-pool components): 4 viewport widths × 9 sections, add/remove/rename/reorder, stable item identity, explicit schedule Load, paste draft and preview stability, sidebar identity, funding edit, keyboard navigation and new-engagement isolation.');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
