const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(__dirname+'/console_v2.html','utf8');
let listener,serial=0;const nodes=new Map();let focus;
const make=(id,tag='textarea')=>({id,tag,value:'',style:{},scrollTop:0,scrollLeft:0,selectionStart:0,selectionEnd:0,selectionDirection:'forward',disabled:true,hasAttribute(k){return k==='oninput'&&tag==='textarea'||k==='data-focus'&&tag==='input';},getAttribute(k){return k==='data-focus'&&tag==='input'?'ordinary':null;},focus(){focus=this;},setSelectionRange(a,b,d){this.selectionStart=a;this.selectionEnd=b;this.selectionDirection=d;},dispatchEvent(){nodes.get(id+'_load').disabled=!this.value;}});
const root={contains:el=>nodes.get(el.id)===el,querySelectorAll:q=>q==='textarea[id]'?[...nodes.values()].filter(n=>n.tag==='textarea'):[]};
function rebuild(){nodes.clear();nodes.set('draft',make('draft'));nodes.set('draft_load',make('draft_load','button'));nodes.set('ordinary',make('ordinary','input'));serial++;}
const document={addEventListener(t,fn){listener=fn;},get activeElement(){return focus;},getElementById:id=>id==='content'?root:nodes.get(id),querySelectorAll:q=>q==='[id]'?[...nodes.values()]:q==='[data-focus]'?[nodes.get('ordinary')]:[]};
const ctx={document,cfg:{},currentTab:'config',window:{scrollX:0,scrollY:700,scrollTo({left,top}){this.scrollX=left;this.scrollY=top;}},Event:class{},queueMicrotask:()=>{},setTimeout:()=>0,restoreCardSelects(){},_decoratePasteSurfaces(){},_renderContentBody:rebuild};
vm.createContext(ctx);vm.runInContext(html.slice(html.indexOf('let _renderedAuthoringTab='),html.indexOf('function _renderContentBody(){')),ctx);
ctx.renderContent();let ta=nodes.get('draft');ta.value='100\t200\t300';ta.setSelectionRange(4,7,'backward');ta.style.height='140px';ta.scrollLeft=30;focus=ta;
ctx.renderContent();ta=nodes.get('draft');assert.equal(ta.value,'100\t200\t300');assert.deepEqual([ta.selectionStart,ta.selectionEnd,ta.selectionDirection],[4,7,'backward']);assert.equal(focus,ta);assert.equal(ta.style.height,'140px');assert.equal(ta.scrollLeft,30);assert.equal(ctx.window.scrollY,700);assert.equal(nodes.get('draft_load').disabled,false);
listener({target:{closest:()=>({textContent:'Load (replace)',closest:()=>({querySelector:()=>ta})})}});ctx.renderContent();assert.equal(nodes.get('draft').value,'');assert.equal(nodes.get('draft_load').disabled,true);
for(const action of ['Clear','Append']){ta=nodes.get('draft');ta.value='1\t2';listener({target:{closest:()=>({textContent:action,closest:()=>({querySelector:()=>ta})})}});ctx.renderContent();assert.equal(nodes.get('draft').value,'');}
nodes.get('draft').value='old engagement';ctx.cfg={};ctx.renderContent();assert.equal(nodes.get('draft').value,'');
focus=nodes.get('ordinary');focus.setSelectionRange(2,3);ctx.renderContent();assert.deepEqual([focus.selectionStart,focus.selectionEnd],[2,3]);
const src=html.slice(html.indexOf('async function preview(){'),html.indexOf('function paintChrome(){'));
(async()=>{for(const tab of ['config','products','is']){let rebuilds=0,updates=0;const c={cfg:{},V3:true,V31:true,currentTab:tab,seq:0,lastRes:null,lastErrs:null,lastRunFailure:null,normalizeCfg(){},syncModules(){},document:{getElementById:id=>id==='status'?{}:null},AbortController,setTimeout,clearTimeout,fetch:async()=>({ok:true,status:200,text:async()=>'{}'}),paintChrome(){},renderContent(){rebuilds++;},refreshConfigPreviews(){updates++;},refreshProductStats(){},refreshFeeCustomerCountPreviews(){}};vm.createContext(c);vm.runInContext(src,c);await c.preview();assert.equal(rebuilds,tab==='is'?1:0);assert.equal(updates,tab==='config'?1:0);}console.log('Passed: draft/caret/focus/scroll/resize preservation, scoped Load/Clear/Append, engagement isolation, preview routing.');})().catch(e=>{console.error(e);process.exit(1)});
