const {parseHTML}=require(process.env.FOUNDRY_DOM_MODULE||'linkedom');const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/console_v2.html','utf8');const {window}=parseHTML(html);const storage=new Map();const ctx={window,document:window.document,console,URL,URLSearchParams,Blob,TextEncoder,TextDecoder,structuredClone,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,fetch:async()=>({ok:false,status:401,json:async()=>({})}),location:{search:'?v=31',pathname:'/console/v2',origin:'http://localhost'},navigator:{},alert(){},confirm:()=>true,Event:window.Event,queueMicrotask};window.scrollTo=()=>{};window.matchMedia=()=>({matches:false,addEventListener(){}});window.localStorage=ctx.localStorage;window.location=ctx.location;window.getComputedStyle=()=>({});
window.V31=true;window.scrollX=0;window.scrollY=0;vm.createContext(ctx);for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){let src=m[1].replace(/renderTabs\(\);\s*whoami\(\)\.then\([\s\S]*$/,'');vm.runInContext(src,ctx);}
vm.runInContext(`cfg=buildEmptyTemplate();currentTab='config';window.V31=true;cfg.assumptions.nie_detail={workforce:{roles:[{role:'Team',count:1,annual_comp:120000},{role:'Directors',count:1,annual_comp:30000}]},categories:[{name:'Technology',amount:100000}]};cfg.assumptions.operating_expense_mode='detailed';console.log('mode',_operatingExpenseMode(cfg.assumptions));renderGlobals();renderConfigTab();`,ctx);
const before=[...window.document.querySelectorAll('#content input,#content select,#content textarea')];vm.runInContext('_iqMountWorkspace()',ctx);console.log('sections', [...window.document.querySelectorAll('.iq-nav button')].map(e=>e.textContent));console.log('control preservation',before.length,before.filter(e=>window.document.getElementById('content').contains(e)).length);console.log('item lists',window.document.querySelectorAll('.iq-item-list').length);
const assert=require('node:assert/strict');assert.equal(before.filter(e=>window.document.getElementById('content').contains(e)).length,before.length);assert.equal(window.document.querySelectorAll('.iq-item-list').length,2);
vm.runInContext("_iqSelectSection('iq-funding')",ctx);assert.equal(window.document.querySelector('#iq-funding').hidden,false);assert.match(window.document.querySelector('#iq-funding').textContent,/Unallocated funding/);assert.equal(window.document.querySelector('#card-sec').hidden,true);assert.match(window.document.querySelector('#card-sec').textContent,/AOCI/);
const globals=window.document.getElementById('globalsBox');vm.runInContext('_iqReturnAssumptions()',ctx);assert.equal(globals.parentElement.tagName,'ASIDE');assert.equal(window.document.querySelector('main > aside').querySelectorAll('#globalsBox').length,1);
vm.runInContext('_iqMountWorkspace();_iqSelectSection("assumptions")',ctx);assert.equal(window.document.getElementById('globalsBox'),globals);assert.equal(window.document.querySelectorAll('#globalsBox').length,1);
vm.runInContext('_iqSelectItem("iq-items-workforce",1)',ctx);assert.equal(window.document.querySelector('[data-workforce-index="1"]').hidden,false);assert.equal(window.document.querySelector('[data-workforce-index="0"]').hidden,true);
assert.equal(window.document.querySelectorAll('#iq-items-workforce .wf-delete').length,2);console.log('PASS sidebar identity/roundtrip, all controls, funding/AOCI separation, workforce selection and remove actions');

vm.runInContext('renderContent()',ctx);assert.ok(window.document.querySelector('#iq-workspace'));assert.equal(window.document.querySelector('main > aside').style.display,'none');
vm.runInContext("currentTab='products';renderContent()",ctx);assert.equal(window.document.getElementById('globalsBox').parentElement.tagName,'ASIDE');assert.equal(window.document.querySelector('main > aside').style.display,'');
vm.runInContext("currentTab='config';renderContent()",ctx);assert.equal(window.document.querySelectorAll('#globalsBox').length,1);assert.ok(window.document.querySelector('#iq-workspace'));console.log('PASS Configuration → Products → Configuration sidebar mounting');
